name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings'
  RUSTDOCFLAGS: '--deny=warnings'
  CARGO_TERM_COLOR: always

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos'] # macos-latest uses aarch64, I think
        lto: ['fat'] # , 'thin', 'false'] # false fixes the error, thin fixes the test but not the original full project
    runs-on: ${{ matrix.os }}-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo do run
        env:
          CARGO_PROFILE_RELEASE_LTO: ${{ matrix.lto }}