name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: '--codegen=debuginfo=0 --deny=warnings'
  RUSTDOCFLAGS: '--deny=warnings'
  CARGO_TERM_COLOR: always

jobs:
  pack-android:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest'] #, 'windows-latest', 'macos-latest'] # same error in other OS
    runs-on: ${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:  
          targets: aarch64-linux-android
      - name: install cargo-ndk
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-ndk
      - name: install cargo-zng
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-zng
      - uses: Swatinem/rust-cache@v2
      - run: cargo do pack android
      - name: upload apk
        uses: actions/upload-artifact@v4
        with:
          name: miscomp-issue-${{ matrix.os }}
          path: target/pack/android/miscomp-issue.apk
          if-no-files-found: error